# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: GPT-OSS 20B
    provider: lmstudio
    model: openai/gpt-oss-20b
    roles: [chat, edit, apply, summarize]
    capabilities:
      - tool_use

  - name: Qwen3 1.7B
    provider: lmstudio
    model: qwen3-1.7b
    roles:
      - autocomplete

  - name: Mxbai Embed V1
    provider: lmstudio
    model: text-embedding-mxbai-embed-large-v1
    roles:
      - embed